# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 17:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_prfn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankBalance', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('town', models.CharField(blank=True, max_length=20)),
                ('zone', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=20)),
                ('member_type', models.IntegerField(default=0)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('emp_prfn_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.Emp_prfn')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.Master')),
            ],
        ),
        migrations.CreateModel(
            name='Task_employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.Employe')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.Employe')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.Master')),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='member',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserAccount.Member'),
        ),
        migrations.AddField(
            model_name='employe',
            name='member',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserAccount.Member'),
        ),
        migrations.AddField(
            model_name='emp_prfn',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.Employe'),
        ),
        migrations.AddField(
            model_name='emp_prfn',
            name='prfn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.Profession'),
        ),
        migrations.AlterUniqueTogether(
            name='emp_prfn',
            unique_together=set([('employe', 'prfn')]),
        ),
    ]
